//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNETSample03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidades
    {
        public int idCidade { get; set; }
        public string descricao { get; set; }
        public string sigla { get; set; }
    }
}
